---
title: "comb_vars"
author: "Samuel Mak"
date: '2023-10-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(devtools)
```


```{r}
#Make some data 
son_sep_23 <- readr::read_csv("https://assets.publishing.service.gov.uk/media/65265dd7aea2d0000d219b3e/Management_information_-_state-funded_schools_-_latest_inspections_at_30_Sep_2023.csv") |> janitor::clean_names() |> as_tibble()

son_sep_23_2 <- son_sep_23 |> 
  select(ofsted_phase, ofsted_region, total_number_of_pupils, overall_effectiveness, publication_date, safeguarding_is_effective) |> 
  mutate(ofsted_phase = factor(ofsted_phase, c("Nursery", "Primary", "Secondary", "PRU", "Special")),
         ofsted_region = as.character(ofsted_region),
         total_number_of_pupils = as.numeric(total_number_of_pupils),
         overall_effectiveness = as.character(overall_effectiveness),
         publication_date = as.Date(publication_date, tryFormats = "%d/%m/%Y"),
         safeguarding_is_effective = ifelse(safeguarding_is_effective == "Yes", T, F))

#Replace some values with NA
{son_sep_23_2$ofsted_phase[sample(nrow(son_sep_23_2), size = 100)] <- NA
son_sep_23_2$overall_effectiveness[sample(nrow(son_sep_23_2), size = 100)] <- NA
son_sep_23_2$ofsted_region[sample(nrow(son_sep_23_2), size = 100)] <- NA
son_sep_23_2$total_number_of_pupils[sample(nrow(son_sep_23_2), size = 100)] <- NA
son_sep_23_2$publication_date[sample(nrow(son_sep_23_2), size = 100)] <- NA
son_sep_23_2$safeguarding_is_effective[sample(nrow(son_sep_23_2), size = 100)] <- NA}
```

```{r}
as_annum <- function(date, from = "09-01", sep = " ", format = "%Y"){
  annum_ending <- as.numeric(format(date, format)) + as.integer(date >= as.Date(paste0(format(date, "%Y"), "-", from), format = "%Y-%m-%d"))
  output <- paste0(annum_ending - 1, sep, annum_ending)
  output[which(is.na(date))] <- NA
  return(output)
}

as_annum(son_sep_23_2$publication_date)
son_sep_23_2 |> mutate(year = as_annum(publication_date))
```

```{r}
#Situations
# Different data types (
# If character, then default to ascending, but can change via options
# If factor, then default to ascending, but can change via options
# If numbers or integers, then ascending, but can change
# If logical, then T first and then F,
# In all cases, NA or NULLs are last

# Arguments
# Groups of variables to be combined
# Name of new variables
# Whether old variables are deleted 
# 
#var <- list(new_variable_1 = c('ofsted_phase', 'ofsted_region'), new_variable_2 = c('overall_effectiveness', 'safeguarding_is_effective', "total_number_of_pupils"))
#data <- son_sep_23_2


comb_vars <- function(data, var, sep = " ", drop = F){
  
  # Change variables to factors and relevel them
  ## Unique combinations in order
  unique_combination_ordered <- lapply(var,FUN = function(x)unique(data[,c(x)])) |> 
    # Ordered unique combinations
    lapply(FUN = function(k){eval(parse(text = paste0("k[order(",paste0("k$", names(k), collapse = ", "), "),]")))}) |> 
    #Combine names 
    lapply(FUN = function(l){eval(parse(text= paste0("paste(", paste0(paste0("l$", names(l)), collapse = ", "), ", sep = sep)")))}) |> 
    lapply(FUN = function(m){paste0("c(", paste0("'",m, "'",collapse = ","), ")")})
  
  # Manipulate the data
  n <- lapply(var, FUN = function(var){paste0("paste(", paste0( paste0("data$", var), collapse = ", "), ", sep = sep)")})
  data[, c(names(var))] <- eval(parse(text = paste0("list(", paste(paste0("factor(",n, ",",unique_combination_ordered, ")"), collapse  = ", "), ")")))
  
  #Drop old columns depending on user
  if(drop){
    data <- data[,!(names(data) %in% unlist(var))]
  }

  return(data)
}

comb_vars(son_sep_23_2, list(phase_region = c('ofsted_phase', 'ofsted_region'), oe_safeguarding_size = c('overall_effectiveness', 'safeguarding_is_effective', "total_number_of_pupils")), drop = T)

lapply(var,FUN = function(x)unique(data[,c(x)])) |> 
  # Ordered unique combinations
  lapply(FUN = function(k){eval(parse(text = paste0("k[order(",paste0("k$", names(k), collapse = ", "), "),]")))}) |> 
  #Combine names 
  lapply(FUN = function(l){eval(parse(text = paste0("c(", paste0("'", paste0("paste(", paste0(paste0("l$", names(l)), collapse = ", "), ", sep = sepp)")))}) 
paste0("paste(", paste0(paste0("l$", names(l[[1]])), collapse = ", "), ", sep = sepp)")
paste0("c(", paste0("'",paste(l[[1]]$ofsted_phase, l[[1]]$ofsted_region, sep = sepp),  "'",collapse = ","), ")")
```


```{r}
names(k[[1]])
c(T, T, F, T, T)[order(c(F, T, F))]
rm(sep)
sepp <- "_"
l[[1]]
paste(l[[1]]$ofsted_phase, l[[1]]$ofsted_region, sep = "")

aiai <- list(factor(paste(son_sep_23_2$ofsted_phase, son_sep_23_2$ofsted_region, sep = "_"), m[[1]]), 
                                       paste(son_sep_23_2$total_number_of_pupils, son_sep_23_2$safeguarding_is_effective, sep = ""))
aiai[[1]] |> levels()
m[[1]]
```


```{r}
son_sep_23_2[, c(names(var) )] <- list(paste(son_sep_23_2$ofsted_phase, son_sep_23_2$ofsted_region, sep = ""), 
                                       paste(son_sep_23_2$total_number_of_pupils, son_sep_23_2$safeguarding_is_effective, sep = ""))

list(paste(son_sep_23_2$ofsted_phase, son_sep_23_2$ofsted_region, sep = ""), 
    paste(son_sep_23_2$total_number_of_pupils, son_sep_23_2$safeguarding_is_effective, sep = ""))

data <- son_sep_23_2

list(paste(data[, c(ofsted_phase)], son_sep_23_2$ofsted_region, sep = ""), 
    paste(son_sep_23_2$total_number_of_pupils, son_sep_23_2$safeguarding_is_effective, sep = ""))

which(names(data) == unlist(var))
data[, c(deparse(substitute(ofsted_phase)))]

deparse(substitute(ofsted_phase + phase))


quote(ofsted)


subset2 <- function(x, condition) {
  condition_call <- substitute(a >= 4)
  r <- eval(condition_call, x)
  x[r, ]
}
subset2(sample_df, a >= 4)
```

```{r}

library(smak)
```















